-- ===========================================================================
-- db_katala -> PostgreSQL (Supabase) migration
-- Converted from: db_katala.sql (MySQL dump, schema only)
-- Run in the Supabase SQL editor, or: psql -f migration.sql
--
-- Key conversions:
--   BIGINT UNSIGNED AUTO_INCREMENT  ->  BIGINT GENERATED BY DEFAULT AS IDENTITY
--   DATETIME                        ->  TIMESTAMP
--   ENGINE=InnoDB / backticks       ->  removed
--   TINYINT(1) BOOLEAN flag columns ->  SMALLINT NOT NULL DEFAULT 1
--                                      (Laravel compares v_isActive with 1/0)
--   ENUM('delivery','pickup')       ->  fulfillment_type enum
--   ON UPDATE CURRENT_TIMESTAMP     ->  set_updated_at() trigger (18 tables)
--   Inline INDEX / UNIQUE KEY       ->  CREATE [UNIQUE] INDEX ... IF NOT EXISTS
--
-- IMPORTANT: Every identifier is double-quoted with the EXACT case used by the
-- Laravel models/controllers (e.g. "tbl_serviceRequest", "v_customerId").
-- PostgreSQL folds unquoted identifiers to lowercase while Laravel's Postgres
-- grammar always quotes identifiers, so the case must match the MySQL dump.
--
-- NOTE for when the Laravel backend is eventually pointed at this database:
-- the raw CONCAT() columns in AdminDataController (dashboard / requests) must
-- quote the column names: COALESCE(c."v_firstName", ...), COALESCE(c."v_lastName", ...).
--
-- All DROP statements are hoisted to the top so the script is re-runnable.
-- After running this, run `php artisan migrate` to create the Sanctum
-- personal_access_tokens table.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Timestamp helper: mimics MySQL's ON UPDATE CURRENT_TIMESTAMP.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW."v_updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Enum used by "tbl_deliveryPickup"."v_fulfillmentType".
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    CREATE TYPE fulfillment_type AS ENUM ('delivery', 'pickup');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- Drop everything first (CASCADE so referencing foreign keys go too).
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS "tbl_customer" CASCADE;
DROP TABLE IF EXISTS "tbl_product" CASCADE;
DROP TABLE IF EXISTS "tbl_productPriceHistory" CASCADE;
DROP TABLE IF EXISTS "tbl_service" CASCADE;
DROP TABLE IF EXISTS "tbl_order" CASCADE;
DROP TABLE IF EXISTS "tbl_orderItem" CASCADE;
DROP TABLE IF EXISTS "tbl_deliveryPickup" CASCADE;
DROP TABLE IF EXISTS "tbl_serviceRequest" CASCADE;
DROP TABLE IF EXISTS "tbl_systemDesign" CASCADE;
DROP TABLE IF EXISTS "tbl_material" CASCADE;
DROP TABLE IF EXISTS "tbl_materialPriceHistory" CASCADE;
DROP TABLE IF EXISTS "tbl_quotation" CASCADE;
DROP TABLE IF EXISTS "tbl_quotationItem" CASCADE;
DROP TABLE IF EXISTS "tbl_project" CASCADE;
DROP TABLE IF EXISTS "tbl_projectMaterial" CASCADE;
DROP TABLE IF EXISTS "tbl_payment" CASCADE;
DROP TABLE IF EXISTS "tbl_projectBilling" CASCADE;
DROP TABLE IF EXISTS "tbl_inventory" CASCADE;
DROP TABLE IF EXISTS "tbl_inventoryTransaction" CASCADE;
DROP TABLE IF EXISTS "tbl_warranty" CASCADE;
DROP TABLE IF EXISTS "tbl_warrantyClaim" CASCADE;
DROP TABLE IF EXISTS "tbl_maintenance" CASCADE;
DROP TABLE IF EXISTS "tbl_role" CASCADE;
DROP TABLE IF EXISTS "tbl_user" CASCADE;
DROP TABLE IF EXISTS "tbl_permission" CASCADE;
DROP TABLE IF EXISTS "tbl_rolePermission" CASCADE;
DROP TABLE IF EXISTS "tbl_activityLog" CASCADE;

-- ---------------------------------------------------------------------------
-- tbl_customer
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_customer" (
    "v_customerId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_customerType" VARCHAR(50) NULL,
    "v_firstName" VARCHAR(100) NULL,
    "v_middleName" VARCHAR(100) NULL,
    "v_lastName" VARCHAR(100) NULL,
    "v_companyName" VARCHAR(150) NULL,
    "v_contactPerson" VARCHAR(150) NULL,
    "v_emailAddress" VARCHAR(150) NULL,
    "v_mobileNumber" VARCHAR(30) NULL,
    "v_telephoneNumber" VARCHAR(30) NULL,
    "v_addressLine" VARCHAR(255) NULL,
    "v_barangay" VARCHAR(100) NULL,
    "v_cityMunicipality" VARCHAR(100) NULL,
    "v_province" VARCHAR(100) NULL,
    "v_postalCode" VARCHAR(20) NULL,
    "v_notes" TEXT NULL,
    "v_isActive" SMALLINT NOT NULL DEFAULT 1,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_customerId")
);
CREATE INDEX IF NOT EXISTS idx_customer_name ON "tbl_customer" ("v_lastName", "v_firstName");
CREATE INDEX IF NOT EXISTS idx_customer_companyName ON "tbl_customer" ("v_companyName");
CREATE INDEX IF NOT EXISTS idx_customer_emailAddress ON "tbl_customer" ("v_emailAddress");

-- ---------------------------------------------------------------------------
-- tbl_product
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_product" (
    "v_productId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_productCode" VARCHAR(60) NULL,
    "v_productName" VARCHAR(150) NOT NULL,
    "v_productCategory" VARCHAR(100) NULL,
    "v_brand" VARCHAR(100) NULL,
    "v_model" VARCHAR(100) NULL,
    "v_productDescription" TEXT NULL,
    "v_unitOfMeasure" VARCHAR(50) NULL,
    "v_currentPrice" NUMERIC(14,2) NULL,
    "v_costPrice" NUMERIC(14,2) NULL,
    "v_supplierReference" VARCHAR(150) NULL,
    "v_warrantyPeriod" VARCHAR(100) NULL,
    "v_isActive" SMALLINT NOT NULL DEFAULT 1,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_productId")
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_productCode ON "tbl_product" ("v_productCode");
CREATE INDEX IF NOT EXISTS idx_product_productName ON "tbl_product" ("v_productName");
CREATE INDEX IF NOT EXISTS idx_product_productCategory ON "tbl_product" ("v_productCategory");

-- ---------------------------------------------------------------------------
-- tbl_productPriceHistory
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_productPriceHistory" (
    "v_productPriceHistoryId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_productId" BIGINT NOT NULL,
    "v_oldPrice" NUMERIC(14,2) NULL,
    "v_newPrice" NUMERIC(14,2) NOT NULL,
    "v_effectiveDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_changeReason" VARCHAR(255) NULL,
    "v_changedByUserId" BIGINT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_productPriceHistoryId"),
    CONSTRAINT fk_productPriceHistory_product
        FOREIGN KEY ("v_productId") REFERENCES "tbl_product"("v_productId")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- tbl_service
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_service" (
    "v_serviceId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_serviceCode" VARCHAR(60) NULL,
    "v_serviceName" VARCHAR(150) NOT NULL,
    "v_serviceCategory" VARCHAR(100) NULL,
    "v_serviceDescription" TEXT NULL,
    "v_basePrice" NUMERIC(14,2) NULL,
    "v_isActive" SMALLINT NOT NULL DEFAULT 1,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_serviceId")
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_service_serviceCode ON "tbl_service" ("v_serviceCode");

-- ---------------------------------------------------------------------------
-- tbl_order
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_order" (
    "v_orderId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_orderNumber" VARCHAR(60) NULL,
    "v_customerId" BIGINT NOT NULL,
    "v_orderDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_orderStatus" VARCHAR(50) NULL,
    "v_subtotalAmount" NUMERIC(14,2) NULL,
    "v_discountAmount" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_deliveryFee" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_taxAmount" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_totalAmount" NUMERIC(14,2) NULL,
    "v_orderNotes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_orderId"),
    CONSTRAINT fk_order_customer
        FOREIGN KEY ("v_customerId") REFERENCES "tbl_customer"("v_customerId")
        ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_order_orderNumber ON "tbl_order" ("v_orderNumber");

-- ---------------------------------------------------------------------------
-- tbl_orderItem
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_orderItem" (
    "v_orderItemId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_orderId" BIGINT NOT NULL,
    "v_productId" BIGINT NOT NULL,
    "v_productNameSnapshot" VARCHAR(150) NULL,
    "v_quantity" NUMERIC(14,2) NOT NULL,
    "v_unitPrice" NUMERIC(14,2) NOT NULL,
    "v_discountAmount" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_lineAmount" NUMERIC(14,2)
        GENERATED ALWAYS AS (("v_quantity" * "v_unitPrice") - "v_discountAmount") STORED,
    "v_notes" TEXT NULL,
    PRIMARY KEY ("v_orderItemId"),
    CONSTRAINT fk_orderItem_order
        FOREIGN KEY ("v_orderId") REFERENCES "tbl_order"("v_orderId")
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_orderItem_product
        FOREIGN KEY ("v_productId") REFERENCES "tbl_product"("v_productId")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- tbl_deliveryPickup
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_deliveryPickup" (
    "v_deliveryPickupId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_orderId" BIGINT NOT NULL,
    "v_fulfillmentType" fulfillment_type NOT NULL,
    "v_recipientName" VARCHAR(150) NULL,
    "v_recipientContactNumber" VARCHAR(30) NULL,
    "v_deliveryAddress" VARCHAR(255) NULL,
    "v_barangay" VARCHAR(100) NULL,
    "v_cityMunicipality" VARCHAR(100) NULL,
    "v_province" VARCHAR(100) NULL,
    "v_postalCode" VARCHAR(20) NULL,
    "v_pickupLocation" VARCHAR(255) NULL,
    "v_scheduledDate" TIMESTAMP NULL,
    "v_completedDate" TIMESTAMP NULL,
    "v_fulfillmentStatus" VARCHAR(50) NULL,
    "v_trackingReference" VARCHAR(100) NULL,
    "v_deliveryPickupNotes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_deliveryPickupId"),
    CONSTRAINT fk_deliveryPickup_order
        FOREIGN KEY ("v_orderId") REFERENCES "tbl_order"("v_orderId")
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- tbl_serviceRequest
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_serviceRequest" (
    "v_serviceRequestId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_serviceRequestNumber" VARCHAR(60) NULL,
    "v_customerId" BIGINT NOT NULL,
    "v_serviceId" BIGINT NULL,
    "v_requestDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_projectName" VARCHAR(150) NULL,
    "v_projectType" VARCHAR(100) NULL,
    "v_buildingStructureType" VARCHAR(100) NULL,
    "v_projectLocation" VARCHAR(255) NULL,
    "v_projectRequirements" TEXT NULL,
    "v_customerConcerns" TEXT NULL,
    "v_preferredSchedule" TIMESTAMP NULL,
    "v_requestStatus" VARCHAR(50) NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_serviceRequestId"),
    CONSTRAINT fk_serviceRequest_customer
        FOREIGN KEY ("v_customerId") REFERENCES "tbl_customer"("v_customerId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_serviceRequest_service
        FOREIGN KEY ("v_serviceId") REFERENCES "tbl_service"("v_serviceId")
        ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_serviceRequest_number ON "tbl_serviceRequest" ("v_serviceRequestNumber");

-- ---------------------------------------------------------------------------
-- tbl_systemDesign
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_systemDesign" (
    "v_systemDesignId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_serviceRequestId" BIGINT NOT NULL,
    "v_designTitle" VARCHAR(150) NULL,
    "v_designDescription" TEXT NULL,
    "v_designFileReference" VARCHAR(255) NULL,
    "v_designVersion" VARCHAR(50) NULL,
    "v_preparedDate" TIMESTAMP NULL,
    "v_presentedDate" TIMESTAMP NULL,
    "v_approvalStatus" VARCHAR(50) NULL,
    "v_approvalDate" TIMESTAMP NULL,
    "v_customerRemarks" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_systemDesignId"),
    CONSTRAINT fk_systemDesign_serviceRequest
        FOREIGN KEY ("v_serviceRequestId") REFERENCES "tbl_serviceRequest"("v_serviceRequestId")
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- tbl_material
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_material" (
    "v_materialId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_materialCode" VARCHAR(60) NULL,
    "v_materialName" VARCHAR(150) NOT NULL,
    "v_materialCategory" VARCHAR(100) NULL,
    "v_materialDescription" TEXT NULL,
    "v_unitOfMeasure" VARCHAR(50) NULL,
    "v_currentPrice" NUMERIC(14,2) NULL,
    "v_costPrice" NUMERIC(14,2) NULL,
    "v_supplierReference" VARCHAR(150) NULL,
    "v_isActive" SMALLINT NOT NULL DEFAULT 1,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_materialId")
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_material_materialCode ON "tbl_material" ("v_materialCode");

-- ---------------------------------------------------------------------------
-- tbl_materialPriceHistory
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_materialPriceHistory" (
    "v_materialPriceHistoryId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_materialId" BIGINT NOT NULL,
    "v_oldPrice" NUMERIC(14,2) NULL,
    "v_newPrice" NUMERIC(14,2) NOT NULL,
    "v_effectiveDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_changeReason" VARCHAR(255) NULL,
    "v_changedByUserId" BIGINT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_materialPriceHistoryId"),
    CONSTRAINT fk_materialPriceHistory_material
        FOREIGN KEY ("v_materialId") REFERENCES "tbl_material"("v_materialId")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- tbl_quotation
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_quotation" (
    "v_quotationId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_quotationNumber" VARCHAR(60) NULL,
    "v_serviceRequestId" BIGINT NOT NULL,
    "v_systemDesignId" BIGINT NULL,
    "v_quotationDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_validUntil" TIMESTAMP NULL,
    "v_subtotalAmount" NUMERIC(14,2) NULL,
    "v_discountAmount" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_taxAmount" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_totalAmount" NUMERIC(14,2) NULL,
    "v_termsAndConditions" TEXT NULL,
    "v_quotationStatus" VARCHAR(50) NULL,
    "v_approvedDate" TIMESTAMP NULL,
    "v_customerRemarks" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_quotationId"),
    CONSTRAINT fk_quotation_serviceRequest
        FOREIGN KEY ("v_serviceRequestId") REFERENCES "tbl_serviceRequest"("v_serviceRequestId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_quotation_systemDesign
        FOREIGN KEY ("v_systemDesignId") REFERENCES "tbl_systemDesign"("v_systemDesignId")
        ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_quotation_number ON "tbl_quotation" ("v_quotationNumber");

-- ---------------------------------------------------------------------------
-- tbl_quotationItem
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_quotationItem" (
    "v_quotationItemId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_quotationId" BIGINT NOT NULL,
    "v_itemType" VARCHAR(50) NULL,
    "v_productId" BIGINT NULL,
    "v_materialId" BIGINT NULL,
    "v_serviceId" BIGINT NULL,
    "v_itemDescription" VARCHAR(255) NOT NULL,
    "v_quantity" NUMERIC(14,2) NOT NULL DEFAULT 1.00,
    "v_unitOfMeasure" VARCHAR(50) NULL,
    "v_unitPrice" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_lineAmount" NUMERIC(14,2)
        GENERATED ALWAYS AS ("v_quantity" * "v_unitPrice") STORED,
    "v_notes" TEXT NULL,
    PRIMARY KEY ("v_quotationItemId"),
    CONSTRAINT fk_quotationItem_quotation
        FOREIGN KEY ("v_quotationId") REFERENCES "tbl_quotation"("v_quotationId")
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_quotationItem_product
        FOREIGN KEY ("v_productId") REFERENCES "tbl_product"("v_productId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_quotationItem_material
        FOREIGN KEY ("v_materialId") REFERENCES "tbl_material"("v_materialId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_quotationItem_service
        FOREIGN KEY ("v_serviceId") REFERENCES "tbl_service"("v_serviceId")
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- tbl_project
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_project" (
    "v_projectId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_projectNumber" VARCHAR(60) NULL,
    "v_serviceRequestId" BIGINT NOT NULL,
    "v_quotationId" BIGINT NULL,
    "v_projectName" VARCHAR(150) NULL,
    "v_projectDescription" TEXT NULL,
    "v_projectLocation" VARCHAR(255) NULL,
    "v_startDate" TIMESTAMP NULL,
    "v_targetCompletionDate" TIMESTAMP NULL,
    "v_actualCompletionDate" TIMESTAMP NULL,
    "v_projectStatus" VARCHAR(50) NULL,
    "v_progressPercentage" NUMERIC(5,2) NULL,
    "v_contractAmount" NUMERIC(14,2) NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_projectId"),
    CONSTRAINT fk_project_serviceRequest
        FOREIGN KEY ("v_serviceRequestId") REFERENCES "tbl_serviceRequest"("v_serviceRequestId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_project_quotation
        FOREIGN KEY ("v_quotationId") REFERENCES "tbl_quotation"("v_quotationId")
        ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_number ON "tbl_project" ("v_projectNumber");

-- ---------------------------------------------------------------------------
-- tbl_projectMaterial
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_projectMaterial" (
    "v_projectMaterialId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_projectId" BIGINT NOT NULL,
    "v_materialId" BIGINT NOT NULL,
    "v_estimatedQuantity" NUMERIC(14,2) NULL,
    "v_actualQuantity" NUMERIC(14,2) NULL,
    "v_unitPrice" NUMERIC(14,2) NULL,
    "v_totalEstimatedAmount" NUMERIC(14,2)
        GENERATED ALWAYS AS (COALESCE("v_estimatedQuantity",0) * COALESCE("v_unitPrice",0)) STORED,
    "v_notes" TEXT NULL,
    PRIMARY KEY ("v_projectMaterialId"),
    CONSTRAINT fk_projectMaterial_project
        FOREIGN KEY ("v_projectId") REFERENCES "tbl_project"("v_projectId")
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_projectMaterial_material
        FOREIGN KEY ("v_materialId") REFERENCES "tbl_material"("v_materialId")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- tbl_payment
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_payment" (
    "v_paymentId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_paymentReferenceNumber" VARCHAR(100) NULL,
    "v_orderId" BIGINT NULL,
    "v_projectId" BIGINT NULL,
    "v_customerId" BIGINT NOT NULL,
    "v_paymentType" VARCHAR(50) NULL,
    "v_paymentMethod" VARCHAR(50) NULL,
    "v_paymentAmount" NUMERIC(14,2) NOT NULL,
    "v_paymentDate" TIMESTAMP NULL,
    "v_paymentStatus" VARCHAR(50) NULL,
    "v_bankName" VARCHAR(150) NULL,
    "v_bankTransactionReference" VARCHAR(150) NULL,
    "v_gatewayName" VARCHAR(100) NULL,
    "v_gatewayTransactionId" VARCHAR(150) NULL,
    "v_receiptReference" VARCHAR(150) NULL,
    "v_verifiedDate" TIMESTAMP NULL,
    "v_verifiedByUserId" BIGINT NULL,
    "v_paymentNotes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_paymentId"),
    CONSTRAINT fk_payment_order
        FOREIGN KEY ("v_orderId") REFERENCES "tbl_order"("v_orderId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_payment_project
        FOREIGN KEY ("v_projectId") REFERENCES "tbl_project"("v_projectId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_payment_customer
        FOREIGN KEY ("v_customerId") REFERENCES "tbl_customer"("v_customerId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_payment_parent CHECK (
        ("v_orderId" IS NOT NULL AND "v_projectId" IS NULL)
        OR
        ("v_orderId" IS NULL AND "v_projectId" IS NOT NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_reference ON "tbl_payment" ("v_paymentReferenceNumber");

-- ---------------------------------------------------------------------------
-- tbl_projectBilling
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_projectBilling" (
    "v_projectBillingId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_projectId" BIGINT NOT NULL,
    "v_billingNumber" VARCHAR(60) NULL,
    "v_billingType" VARCHAR(50) NULL,
    "v_progressPercentage" NUMERIC(5,2) NULL,
    "v_billingAmount" NUMERIC(14,2) NOT NULL,
    "v_billingDate" TIMESTAMP NULL,
    "v_dueDate" TIMESTAMP NULL,
    "v_billingStatus" VARCHAR(50) NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_projectBillingId"),
    CONSTRAINT fk_projectBilling_project
        FOREIGN KEY ("v_projectId") REFERENCES "tbl_project"("v_projectId")
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_projectBilling_number ON "tbl_projectBilling" ("v_billingNumber");

-- ---------------------------------------------------------------------------
-- tbl_inventory
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_inventory" (
    "v_inventoryId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_productId" BIGINT NULL,
    "v_materialId" BIGINT NULL,
    "v_quantityOnHand" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_quantityReserved" NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    "v_quantityAvailable" NUMERIC(14,2)
        GENERATED ALWAYS AS ("v_quantityOnHand" - "v_quantityReserved") STORED,
    "v_reorderLevel" NUMERIC(14,2) NULL,
    "v_storageLocation" VARCHAR(150) NULL,
    "v_lastStockUpdate" TIMESTAMP NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_inventoryId"),
    CONSTRAINT fk_inventory_product
        FOREIGN KEY ("v_productId") REFERENCES "tbl_product"("v_productId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_material
        FOREIGN KEY ("v_materialId") REFERENCES "tbl_material"("v_materialId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_item CHECK (
        ("v_productId" IS NOT NULL AND "v_materialId" IS NULL)
        OR
        ("v_productId" IS NULL AND "v_materialId" IS NOT NULL)
    )
);

-- ---------------------------------------------------------------------------
-- tbl_inventoryTransaction
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_inventoryTransaction" (
    "v_inventoryTransactionId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_inventoryId" BIGINT NOT NULL,
    "v_transactionType" VARCHAR(50) NULL,
    "v_quantity" NUMERIC(14,2) NOT NULL,
    "v_referenceType" VARCHAR(50) NULL,
    "v_referenceId" BIGINT NULL,
    "v_transactionDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_reason" VARCHAR(255) NULL,
    "v_performedByUserId" BIGINT NULL,
    "v_notes" TEXT NULL,
    PRIMARY KEY ("v_inventoryTransactionId"),
    CONSTRAINT fk_inventoryTransaction_inventory
        FOREIGN KEY ("v_inventoryId") REFERENCES "tbl_inventory"("v_inventoryId")
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------------
-- tbl_warranty
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_warranty" (
    "v_warrantyId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_warrantyNumber" VARCHAR(60) NULL,
    "v_customerId" BIGINT NOT NULL,
    "v_orderId" BIGINT NULL,
    "v_projectId" BIGINT NULL,
    "v_productId" BIGINT NULL,
    "v_warrantyType" VARCHAR(50) NULL,
    "v_startDate" TIMESTAMP NULL,
    "v_endDate" TIMESTAMP NULL,
    "v_coverageDetails" TEXT NULL,
    "v_termsAndConditions" TEXT NULL,
    "v_warrantyStatus" VARCHAR(50) NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_warrantyId"),
    CONSTRAINT fk_warranty_customer
        FOREIGN KEY ("v_customerId") REFERENCES "tbl_customer"("v_customerId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_warranty_order
        FOREIGN KEY ("v_orderId") REFERENCES "tbl_order"("v_orderId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_warranty_project
        FOREIGN KEY ("v_projectId") REFERENCES "tbl_project"("v_projectId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_warranty_product
        FOREIGN KEY ("v_productId") REFERENCES "tbl_product"("v_productId")
        ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_warranty_number ON "tbl_warranty" ("v_warrantyNumber");

-- ---------------------------------------------------------------------------
-- tbl_warrantyClaim
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_warrantyClaim" (
    "v_warrantyClaimId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_warrantyId" BIGINT NOT NULL,
    "v_claimNumber" VARCHAR(60) NULL,
    "v_claimDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_concernDescription" TEXT NOT NULL,
    "v_claimStatus" VARCHAR(50) NULL,
    "v_resolutionDetails" TEXT NULL,
    "v_resolvedDate" TIMESTAMP NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_warrantyClaimId"),
    CONSTRAINT fk_warrantyClaim_warranty
        FOREIGN KEY ("v_warrantyId") REFERENCES "tbl_warranty"("v_warrantyId")
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_warrantyClaim_number ON "tbl_warrantyClaim" ("v_claimNumber");

-- ---------------------------------------------------------------------------
-- tbl_maintenance
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_maintenance" (
    "v_maintenanceId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_maintenanceNumber" VARCHAR(60) NULL,
    "v_customerId" BIGINT NOT NULL,
    "v_projectId" BIGINT NULL,
    "v_warrantyId" BIGINT NULL,
    "v_serviceId" BIGINT NULL,
    "v_maintenanceType" VARCHAR(100) NULL,
    "v_equipmentSystemDescription" TEXT NULL,
    "v_location" VARCHAR(255) NULL,
    "v_scheduledDate" TIMESTAMP NULL,
    "v_completedDate" TIMESTAMP NULL,
    "v_maintenanceStatus" VARCHAR(50) NULL,
    "v_findings" TEXT NULL,
    "v_actionsPerformed" TEXT NULL,
    "v_recommendations" TEXT NULL,
    "v_nextMaintenanceDate" TIMESTAMP NULL,
    "v_notes" TEXT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_maintenanceId"),
    CONSTRAINT fk_maintenance_customer
        FOREIGN KEY ("v_customerId") REFERENCES "tbl_customer"("v_customerId")
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_maintenance_project
        FOREIGN KEY ("v_projectId") REFERENCES "tbl_project"("v_projectId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_maintenance_warranty
        FOREIGN KEY ("v_warrantyId") REFERENCES "tbl_warranty"("v_warrantyId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_maintenance_service
        FOREIGN KEY ("v_serviceId") REFERENCES "tbl_service"("v_serviceId")
        ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_maintenance_number ON "tbl_maintenance" ("v_maintenanceNumber");

-- ---------------------------------------------------------------------------
-- tbl_role
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_role" (
    "v_roleId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_roleName" VARCHAR(100) NOT NULL,
    "v_roleDescription" VARCHAR(255) NULL,
    "v_isActive" SMALLINT NOT NULL DEFAULT 1,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_roleId")
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_role_roleName ON "tbl_role" ("v_roleName");

-- ---------------------------------------------------------------------------
-- tbl_user
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_user" (
    "v_userId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_roleId" BIGINT NULL,
    "v_customerId" BIGINT NULL,
    "v_userName" VARCHAR(100) NOT NULL,
    "v_passwordHash" VARCHAR(255) NULL,
    "v_firstName" VARCHAR(100) NULL,
    "v_lastName" VARCHAR(100) NULL,
    "v_emailAddress" VARCHAR(150) NULL,
    "v_mobileNumber" VARCHAR(30) NULL,
    "v_accountStatus" VARCHAR(50) NULL,
    "v_lastLoginAt" TIMESTAMP NULL,
    "v_isActive" SMALLINT NOT NULL DEFAULT 1,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "v_updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_userId"),
    CONSTRAINT fk_user_role
        FOREIGN KEY ("v_roleId") REFERENCES "tbl_role"("v_roleId")
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_user_customer
        FOREIGN KEY ("v_customerId") REFERENCES "tbl_customer"("v_customerId")
        ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_userName ON "tbl_user" ("v_userName");
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_emailAddress ON "tbl_user" ("v_emailAddress");

-- ---------------------------------------------------------------------------
-- tbl_permission
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_permission" (
    "v_permissionId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_permissionCode" VARCHAR(100) NOT NULL,
    "v_permissionName" VARCHAR(150) NOT NULL,
    "v_permissionDescription" VARCHAR(255) NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_permissionId")
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_permission_code ON "tbl_permission" ("v_permissionCode");

-- ---------------------------------------------------------------------------
-- tbl_rolePermission
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_rolePermission" (
    "v_rolePermissionId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_roleId" BIGINT NOT NULL,
    "v_permissionId" BIGINT NOT NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_rolePermissionId"),
    CONSTRAINT fk_rolePermission_role
        FOREIGN KEY ("v_roleId") REFERENCES "tbl_role"("v_roleId")
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_rolePermission_permission
        FOREIGN KEY ("v_permissionId") REFERENCES "tbl_permission"("v_permissionId")
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_rolePermission_pair ON "tbl_rolePermission" ("v_roleId", "v_permissionId");

-- ---------------------------------------------------------------------------
-- tbl_activityLog
-- ---------------------------------------------------------------------------
CREATE TABLE "tbl_activityLog" (
    "v_activityLogId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "v_userId" BIGINT NULL,
    "v_actionType" VARCHAR(100) NOT NULL,
    "v_tableName" VARCHAR(100) NULL,
    "v_recordId" BIGINT NULL,
    "v_actionDescription" TEXT NULL,
    "v_ipAddress" VARCHAR(45) NULL,
    "v_createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("v_activityLogId"),
    CONSTRAINT fk_activityLog_user
        FOREIGN KEY ("v_userId") REFERENCES "tbl_user"("v_userId")
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ---------------------------------------------------------------------------
-- Triggers emulating MySQL's ON UPDATE CURRENT_TIMESTAMP.
-- ---------------------------------------------------------------------------
CREATE TRIGGER trg_tbl_customer_updatedAt BEFORE UPDATE ON "tbl_customer"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_product_updatedAt BEFORE UPDATE ON "tbl_product"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_service_updatedAt BEFORE UPDATE ON "tbl_service"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_order_updatedAt BEFORE UPDATE ON "tbl_order"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_deliveryPickup_updatedAt BEFORE UPDATE ON "tbl_deliveryPickup"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_serviceRequest_updatedAt BEFORE UPDATE ON "tbl_serviceRequest"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_systemDesign_updatedAt BEFORE UPDATE ON "tbl_systemDesign"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_material_updatedAt BEFORE UPDATE ON "tbl_material"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_quotation_updatedAt BEFORE UPDATE ON "tbl_quotation"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_project_updatedAt BEFORE UPDATE ON "tbl_project"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_payment_updatedAt BEFORE UPDATE ON "tbl_payment"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_projectBilling_updatedAt BEFORE UPDATE ON "tbl_projectBilling"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_inventory_updatedAt BEFORE UPDATE ON "tbl_inventory"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_warranty_updatedAt BEFORE UPDATE ON "tbl_warranty"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_warrantyClaim_updatedAt BEFORE UPDATE ON "tbl_warrantyClaim"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_maintenance_updatedAt BEFORE UPDATE ON "tbl_maintenance"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_role_updatedAt BEFORE UPDATE ON "tbl_role"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tbl_user_updatedAt BEFORE UPDATE ON "tbl_user"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Foreign keys that reference "tbl_user" (user-created timestamp columns).
-- ---------------------------------------------------------------------------
ALTER TABLE "tbl_productPriceHistory"
    ADD CONSTRAINT fk_productPriceHistory_user
        FOREIGN KEY ("v_changedByUserId") REFERENCES "tbl_user"("v_userId")
        ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "tbl_materialPriceHistory"
    ADD CONSTRAINT fk_materialPriceHistory_user
        FOREIGN KEY ("v_changedByUserId") REFERENCES "tbl_user"("v_userId")
        ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "tbl_payment"
    ADD CONSTRAINT fk_payment_verifiedByUser
        FOREIGN KEY ("v_verifiedByUserId") REFERENCES "tbl_user"("v_userId")
        ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "tbl_inventoryTransaction"
    ADD CONSTRAINT fk_inventoryTransaction_user
        FOREIGN KEY ("v_performedByUserId") REFERENCES "tbl_user"("v_userId")
        ON UPDATE CASCADE ON DELETE SET NULL;